source 'https://rubygems.org'

#Rack provides a minimal, modular and adaptable interface for developing web applications in Ruby
gem 'rack'
#Grape allows you to build lightweight APIs with Ruby 
gem 'grape'
#provides an autogenerated documentation for your Grape API
gem 'grape-swagger'

#Rake is a Make-like program implemented in Ruby
gem 'rake'

# Here elasticsearch is used as a cache and datastore
gem 'elasticsearch-persistence'

#console for Rack based ruby web applications.
gem 'racksh'



group :test do
  gem 'rspec'
  gem 'rack-test', require: 'rack/test'
  #stubbing and setting expectations on HTTP requests in Ruby
  gem 'webmock'
end